# Generated by Django 4.2.4 on 2023-08-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numberids", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fname", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50, unique=True)),
                ("lname", models.CharField(max_length=50)),
                ("uname", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=500)),
                ("idpic", models.ImageField(upload_to="idimg/")),
                ("Otp", models.CharField(max_length=10)),
                ("account_no", models.CharField(max_length=16)),
                ("account_balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Account_maintain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("transaction_type", models.CharField(max_length=100)),
                ("account_update_balance", models.IntegerField(default=0)),
                (
                    "coustmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.registration",
                    ),
                ),
            ],
        ),
    ]
