# Generated by Django 4.2.4 on 2023-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fname", models.CharField(max_length=50)),
                ("phone", models.IntegerField(unique=True)),
                ("lname", models.CharField(max_length=50)),
                ("uname", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("rpassword", models.CharField(max_length=50)),
                ("idpic", models.ImageField(upload_to="idimg/")),
            ],
        ),
    ]
