# Generated by Django 4.2.4 on 2023-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="rpassword",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
