# Generated by Django 4.2.4 on 2023-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="phone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
