# Generated by Django 4.2.4 on 2023-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_registration_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="Otp",
            field=models.CharField(default=" ", max_length=10),
            preserve_default=False,
        ),
    ]
