# Generated by Django 4.1.3 on 2023-08-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register_user_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_maintain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.IntegerField()),
                ('transaction_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(max_length=100)),
                ('coustmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.register_user')),
            ],
        ),
    ]
