# Generated by Django 4.2.4 on 2023-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_registration_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="password",
            field=models.CharField(max_length=500),
        ),
    ]
