# Generated by Django 4.1.3 on 2023-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_account_maintain_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
