# Generated by Django 4.1.3 on 2023-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_register_user_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_maintain',
            name='account_update_balance',
            field=models.IntegerField(default=0),
        ),
    ]
