# Generated by Django 4.1.3 on 2023-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_account_maintain_account_update_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_maintain',
            name='reason',
            field=models.CharField(default='', max_length=150),
        ),
    ]
