# Generated by Django 4.1.3 on 2023-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_account_maintain_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_maintain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
